export const queryKeys = {
  analytics: (role) => ['analytics', role],
  users: (params) => ['users', params],
  queries: (params) => ['queries', params],
  myQueries: (params) => ['queries', 'mine', params],
  publicQueries: (params) => ['queries', 'public', params],
  staffPendingQueries: (params) => ['queries', 'staff', 'pending', params],
  staffReplies: (params) => ['queries', 'staff', 'my-replies', params],
  adminQueries: (params) => ['queries', 'admin', params],
  adminQueryDetail: (id) => ['queries', 'admin', 'detail', id],
  adminUserActivity: (userId) => ['queries', 'admin', 'activity', userId],
  queryDetail: (id) => ['queries', 'detail', id],
  recommendations: ['recommendations'],
  products: (params) => ['products', params],
  productDetail: (id) => ['products', 'detail', id],
  categories: (params = {}) => ['categories', params],
  categoryDetail: (id) => ['categories', 'detail', id],
  cropDetails: (params) => ['crop-details', params],
  cropDiseases: (params = {}) => ['crop-diseases', params],
  cropDiseaseDetail: (id) => ['crop-diseases', 'detail', id],
  guideHeadings: ['guide-headings'],
  guideHeadingDetail: (id) => ['guide-headings', 'detail', id],
  guideDetails: ['guide-details'],
  guideDetailsByCrop: (cropId) => ['guide-details', 'crop', cropId],
  orders: (params) => ['orders', params],
  escalations: (params) => ['escalations', params],
  notifications: (params) => ['notifications', params],
  auditLogs: ['audit-logs'],
  tasks: (params) => ['tasks', params],
  supportCases: ['support-cases'],
  settings: ['settings'],
}
