import { zodResolver } from '@hookform/resolvers/zod'
import { UserPlus } from 'lucide-react'
import { useForm } from 'react-hook-form'
import { Link, useNavigate } from 'react-router-dom'
import { toast } from 'sonner'
import { z } from 'zod'
import { Field } from '@/components/forms/field'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { AuthCard } from '@/features/auth/components/auth-card'
import { useRegisterMutation } from '@/services/api/hooks'

const schema = z.object({
  username: z.string().min(2, 'Username is required'),
  phone: z.string().regex(/^\d{10}$/, 'Phone number must be 10 digits'),
  password: z.string().min(6, 'Password must be at least 6 characters'),
  profile_image: z
    .any()
    .optional()
    .refine((files) => !files?.length || files[0].size <= 50 * 1024 * 1024, 'Profile image must be 50MB or smaller'),
})

export default function RegisterPage() {
  const navigate = useNavigate()
  const mutation = useRegisterMutation()
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm({
    resolver: zodResolver(schema),
    defaultValues: {
      username: '',
      phone: '',
      password: '',
    },
  })

  const onSubmit = async (values) => {
    try {
      await mutation.mutateAsync(values)
      toast.success('Account created. Verify the OTP saved for your phone number.')
      navigate(`/verify-otp?phone=${encodeURIComponent(values.phone)}`)
    } catch (error) {
      toast.error(error.displayMessage || 'Unable to create account.')
    }
  }

  return (
    <AuthCard
      title="Create account"
      description="Register with your username and phone number, then verify the OTP generated by the backend."
      footer={
        <p className="text-sm text-slate-500">
          Already verified?{' '}
          <Link to="/login" className="font-semibold text-primary">
            Sign in
          </Link>
        </p>
      }
    >
      <form className="space-y-4" onSubmit={handleSubmit(onSubmit)}>
        <Field label="Username" error={errors.username?.message}>
          <Input placeholder="Enter username" {...register('username')} />
        </Field>
        <Field label="Phone number" error={errors.phone?.message}>
          <Input inputMode="numeric" placeholder="9876543210" {...register('phone')} />
        </Field>
        <Field label="Password" error={errors.password?.message}>
          <Input type="password" placeholder="Minimum 6 characters" {...register('password')} />
        </Field>
        <Field label="Profile image" hint="Optional JPEG, PNG, JPG, or MP4 up to 50MB." error={errors.profile_image?.message}>
          <Input type="file" accept="image/jpeg,image/png,image/jpg,video/mp4" {...register('profile_image')} />
        </Field>
        <Button type="submit" className="w-full" size="lg" disabled={mutation.isPending}>
          <UserPlus className="h-4 w-4" />
          {mutation.isPending ? 'Creating...' : 'Create account'}
        </Button>
      </form>
    </AuthCard>
  )
}
